#!/usr/bin/env bash

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$CONFIGS" ] || [ ! -d "$SECRETS" ]; then
    echo "Configs or secrets directory are missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export RSYSLOG_REPLICAS=$(count "$RSYSLOG_NODES")
}

function stack_clean {
  echo "Removing $STACK..."
  docker stack rm "$STACK" --detach=false
}

function stack_env {
  echo
  echo "DOCKER IMAGE  = $RSYSLOG_IMAGE"
  echo "RSYSLOG NODES = ($RSYSLOG_REPLICAS)"
  list "$RSYSLOG_NODES"
  echo
  echo "UDP/TCP PORT  = $UDP_PORT/$TCP_PORT"
  echo
}

function stack_deploy {
  docker stack deploy --detach=true -c rsyslog.yml "$STACK"
}
