#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function build_configs {
  find "$CONFIGS" -maxdepth 1 -type f -name '*.tmpl' | while IFS= read -r tmpl; do
    local out="${tmpl%.tmpl}"
    envsubst < "$tmpl" > "$out"
  done
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$CONFIGS" ] || [ ! -d "$SECRETS" ]; then
    echo "Configs or secrets directory are missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export RSYSLOG_REPLICAS=$(count "$RSYSLOG_NODES")
}

function stack_env {
  echo
  echo "DOCKER IMAGE  = $RSYSLOG_IMAGE"
  echo "RSYSLOG NODES = ($RSYSLOG_REPLICAS)"
  list "$RSYSLOG_NODES"
  echo
  echo "UDP/TCP PORT  = $RSYSLOG_UDP_PORT/$RSYSLOG_TCP_PORT"
  echo
}

function stack_deploy {
  build_configs
  docker stack deploy --detach=true -c rsyslog.yml "$STACK"
}
